version: 2.1

jobs:
  setup_mongodb:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Start MongoDB
          command: |
            docker run -d --name mongodb -p 27017:27017 mongo:latest
            sleep 10 

  build_and_test:
    docker:
      - image: circleci/node:14
        environment:
          MONGO_URL: mongodb://localhost:27017/Hangman
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Node.js server
          command: node index.js

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - setup_mongodb
      - build_and_test:
          requires:
            - setup_mongodb
